### PR TITLE
Use blue text instead of red borders for QTR hyperlinks

### PR DESCRIPTION
**Pull request by bmerry**
I find it a bit more comfortable to read.

Checklist (if not applicable, edit to add `(N/A)` and mark as done):

- [x] (N/A) If dependencies are added/removed: update `setup.cfg` and `.pre-commit-config.yaml`
- [x] (N/A) If modules are added/removed: use sphinx-apidoc to update files in `doc/`
- [x] Ensure copyright notices are present and up-to-date
- [x] If qualification tests are changed: attach a sample qualification report
- [x] (N/A) If design has changed: ensure documentation is up to date
- [x] (N/A) If ICD-defined sensors have been added: update `fake_servers.py` in katsdpcontroller to match

### CODE REVIEW

**Comment by bmerry** [comment]
An example report: [test.pdf](https://github.com/ska-sa/katgpucbf/files/10697167/test.pdf)

**Comment by bmerry** [comment]
@tyronevb we need a casting vote: I think this looks better, but James prefers the original of a coloured border around links.

**Comment by bmerry** [comment]
@tyronevb ping

**Review by tyronevb — CHANGES_REQUESTED** [review]
I'm a bit conflicted:

- the blue text is certainly easier on the eyes than the red borders (especially in cases where there are links on successive lines in a table)
- it isn't _as obvious_ that it's a hyperlink in some cases

Is there a way to make is a bit more obvious? One idea is to underline them as well (but not the links in the TOC), but I'm not how that'll look in the larger tables which contain lots of links.

**Comment by james-smith-za** [comment]
> Is there a way to make is a bit more obvious? One idea is to underline them as well (but not the links in the TOC), but I'm not how that'll look in the larger tables which contain lots of links.

I'm not sure that there's a way to do it selectively unless you do it manually.
I think you can do links without formatting then manually format each link, but that would be too much of a pain.

**Comment by bmerry** [comment]
It's easy enough to underline the links we add to the body. I've attached a sample showing what that would look like.
[report.pdf](https://github.com/ska-sa/katgpucbf/files/10883267/report.pdf)

**Comment by james-smith-za** [comment]
I'd rather go with plain blue text than underlined. Since a lot of the links are in tables, the blue underline and the table cell boundaries don't look nice so close together.

If we want to get rid of the red boxes, it doesn't make sense to replace them with something that's almost equally unpleasant.

I'll withdraw my objection if you feel strongly about it.

**Comment by tyronevb** [comment]
Thanks, @bmerry.

Yeah, the underlined text looks messy in the tables. Let's rather go with the plain blue text.

**Pull request merged**
